---
title: "library_test"
output: html_document
---

# dplyr
```{r}
install.packages('dplyr')
library('dplyr')
?dplyr
#mtcars 데이터 불러오기
cars<-mtcars
cars
```

```{r}
# data.frame을 dplyr용으로 변환
cars_dp<-tbl_df(cars)
cars_dp
```

```{r}
#180마력 이상, 자동변속 자동차만 구분해서 보기
filter(cars_dp, hp>=180, am==0)
```

```{r}
#필터링 한 데이터를 hope_list1에 넣겠다.
hope_list1<-filter(cars_dp, hp>=180, am==0)
hope_list1
```

```{r}
#mpg가 낮은 순으로 배열하겠다.
arrange(hope_list1, mpg)
#arrange(hope_list1, wt, hp, mpg)
#arrange(hope_list1, desc(mpg))
```

```{r}
#hope_list1_ma에 배열한 것을 넣겠다.
hope_list1_ma<-arrange(hope_list1, mpg)
hope_list1_ma
```

#ggplot2
```{r}
library('ggplot2')
# 내장데이터인 iris 데이터를 이용하겠다.
iris
# ggplot함수를 이용한다. data는 iris를 이용, 
# x축을 Sepal.Length, y축을 Sepal.Width
g<-ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width))
g
# 원하는 모양을 입력
# 산점도를 이용하겠다.
g+geom_point()
# 산점도에 색상, 크기, 디자인을 넣어보겠다. 
g+geom_point(aes(color=Species, shape=Species), size=5)
```

#sqldf
```{r}
install.packages('sqldf')
library('sqldf')
# googleVis 패키지 설치해서 Fruits 데이터 불러오기
install.packages('googleVis')
library('googleVis')
Fruits

# Fruit값이 Apples 인 값들의 모든 정보 조회
sqldf('SELECT*FROM Fruits WHERE Fruit=\'Apples\'')

# Fruits 데이터셋에서 Fruit 값이 Apples 이고 Year 값이 2008인 행을 삭제
sqldf(c('DELETE FROM Fruits WHERE Fruit="Apples" AND Year=2008', 'SELECT*FROM Fruits'))
```

#randomForest
```{r}
install.packages('randomForest')
library('randomForest')
# MASS 라이브러리의 예제 데이터를 사용하겠다.
install.packages('MASS')
library('MASS')
# 피마 인디언 중 21세 이상의 
# 성인 여성의 건강상태 데이터 불러오기 
# data()를 사용하면 그 이름을 그대로 데이터프레임으로 사용.
data('Pima.tr')
data('Pima.te')

#ls()
#search()
#rm('Pima.te')

# 모형을 만든다 = 시드를 만든다.
set.seed(10)
rf.fit=randomForest(type~npreg+glu+bp+skin+bmi+ped+age,
                    data=Pima.tr, mtry=floor(sqrt(7)), ntree=500,importance=T)
rf.fit

# 테스트 데이터에서 독립변수, 종속변수 나눠주기
test_x=Pima.te[c('npreg', 'glu', 'bp', 'skin', 'bmi', 'ped', 'age')]
test_y=Pima.te$type


# 성능 평가하기
y_pred=predict(rf.fit, test_x)
install.packages('caret')
install.packages('e1071', dependencies=TRUE)
library('caret')
confusionMatrix(y_pred, test_y)

# 변수중요도
importance(rf.fit)
```
